name: One-off Firestore Backfill

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (no writes)"
        required: true
        default: 'true'
      overwrite:
        description: "Overwrite existing docs if present"
        required: true
        default: 'false'
      limit:
        description: "Process at most N files (0 = all)"
        required: false
        default: '0'
      max_size_mb:
        description: "Skip files larger than this size in MB"
        required: false
        default: '0.95'
      log_level:
        description: "Logging level (DEBUG, INFO, WARNING, ERROR)"
        required: false
        default: 'INFO'

jobs:
  backfill:
    runs-on: ubuntu-latest
    # 환경 시크릿을 사용하는 경우 여기를 환경 이름으로 바꾸세요 (예: CloudRun)
    environment: Back_Fill
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run backfill
        env:
          # Firestore settings (필요한 값들을 시크릿 또는 변수로 제공)
          FIRESTORE_ENABLED: 'true'
          GCP_PROJECT: ${{ secrets.GCP_PROJECT || vars.GCP_PROJECT || secrets.GCP_PROJECT_ID || vars.GCP_PROJECT_ID }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID || vars.GCP_PROJECT_ID || secrets.GCP_PROJECT || vars.GCP_PROJECT }}
          # GCP_SA_KEY는 파일 경로, RAW JSON, Base64 JSON 모두 허용됩니다.
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          set -euo pipefail
          DRY_RUN="${{ github.event.inputs.dry_run }}"
          OVERWRITE="${{ github.event.inputs.overwrite }}"
          LIMIT="${{ github.event.inputs.limit }}"
          MAX_SIZE_MB="${{ github.event.inputs.max_size_mb }}"
          LOG_LEVEL="${{ github.event.inputs.log_level }}"

          ARGS=()
          [ "${DRY_RUN}" = "true" ] && ARGS+=("--dry-run")
          [ "${OVERWRITE}" = "true" ] && ARGS+=("--overwrite")
          [ -n "${LIMIT}" ] && [ "${LIMIT}" != "0" ] && ARGS+=("--limit" "${LIMIT}")
          [ -n "${MAX_SIZE_MB}" ] && ARGS+=("--max-size-mb" "${MAX_SIZE_MB}")
          [ -n "${LOG_LEVEL}" ] && ARGS+=("--log-level" "${LOG_LEVEL}")

          echo "Running: python -m app.scripts.backfill_firestore ${ARGS[*]}"
          python -m app.scripts.backfill_firestore "${ARGS[@]}"
